---
-
  hosts: all

  tasks:

    - name: Stop ActiveMQ
      service:
        name: activemq
        state: stopped

    - name: sleep 5
      command: sleep 5

    - name: Start ActiveMQ
      service:
        name: activemq
        state: started
