---
-
  hosts: all
  become: true
  remote_user: localansible-eto

  tasks:

    - name: Stop ActiveMQ
      become: true
      become_user: root
      command: service activemq stop

    - name: sleep 10
      become: true
      become_user: root
      command: sleep 10

    - name: Start ActiveMQ
      become: yes
      become_user: root
      command: service activemq start
